p='www/js/games/board.js'; s=open(p,encoding='utf-8').read()
def rep(a,b,cnt=1):
    global s
    assert s.count(a)==cnt, (a[:60], s.count(a))
    s=s.replace(a,b)
# connect4
rep("const { h } = api; const W = 7, H = 6; let b, over, cells, st = stats(api, 'connect4');\n      function start() { b = Array(W * H).fill(0); over = false; render(); }",
    "const { h } = api; const W = 7, H = 6; let b, over, cells, st = stats(api, 'connect4'), diff = 1;\n      function start() { b = Array(W * H).fill(0); over = false; render(); }")
rep("const v = minimax(b, 4, 1, -Infinity, Infinity); b[r * W + c] = 0; if (v > bestV) { bestV = v; bestCol = c; } } drop(bestCol, 2);",
    "const v = minimax(b, [1, 4, 7][diff], 1, -Infinity, Infinity); b[r * W + c] = 0; if (v > bestV) { bestV = v; bestCol = c; } } if (diff === 0 && Math.random() < 0.5) { const free = [0, 1, 2, 3, 4, 5, 6].filter(c => !b[c]); bestCol = free[api.rand(0, free.length - 1)]; } drop(bestCol, 2);")
rep("      start();\n    }\n  });\n\n  /* ---------- Реверси ---------- */","      api.difficulty('connect4', d => { diff = d; start(); });\n    }\n  });\n\n  /* ---------- Реверси ---------- */")
# reversi
rep("let b, cells, hdr, over, st = stats(api, 'reversi');","let b, cells, hdr, over, st = stats(api, 'reversi'), diff = 1;")
rep("const CORN = [0, 7, 56, 63]; let best = m[0], bv = -1; for (const k of m) { let v = flips(b, k, 2).length + (CORN.includes(k) ? 20 : 0) - ([1, 8, 9, 6, 14, 15, 48, 49, 57, 54, 55, 62].includes(k) ? 5 : 0); if (v > bv) { bv = v; best = k; } } apply(best, 2);",
    "const CORN = [0, 7, 56, 63], BAD = [1, 8, 9, 6, 14, 15, 48, 49, 57, 54, 55, 62]; const evalB = g => g.reduce((s, v, k) => s + (v ? (v === 2 ? 1 : -1) * (CORN.includes(k) ? 12 : BAD.includes(k) ? -3 : (k % 8 === 0 || k % 8 === 7 || k < 8 || k > 55) ? 3 : 1) : 0), 0); const search = (g, pl, depth) => { const mv = [...Array(64).keys()].filter(i => flips(g, i, pl).length); if (!depth || !mv.length) return evalB(g); let best = pl === 2 ? -Infinity : Infinity; for (const k of mv) { const g2 = g.slice(); flips(g2, k, pl).forEach(x => g2[x] = pl); g2[k] = pl; const v = search(g2, 3 - pl, depth - 1); best = pl === 2 ? Math.max(best, v) : Math.min(best, v); } return best; }; let best = m[0], bv = -Infinity; for (const k of m) { let v; if (diff === 0) v = Math.random(); else if (diff === 1) v = flips(b, k, 2).length + (CORN.includes(k) ? 20 : 0) - (BAD.includes(k) ? 5 : 0); else { const g2 = b.slice(); flips(g2, k, 2).forEach(x => g2[x] = 2); g2[k] = 2; v = search(g2, 1, 3); } if (v > bv) { bv = v; best = k; } } apply(best, 2);")
rep("      start();\n    }\n  });\n\n  /* ---------- Точки и квадраты ---------- */","      api.difficulty('reversi', d => { diff = d; start(); });\n    }\n  });\n\n  /* ---------- Точки и квадраты ---------- */")
# dots
rep("let hl, vl, boxes, turn, cv, ctx, over, st = stats(api, 'dots'), hdr;","let hl, vl, boxes, turn, cv, ctx, over, st = stats(api, 'dots'), hdr, diff = 1;")
rep("let pick = free.find(([k, i]) => boxesOf(k, i).some(bi => sides(bi) === 3));\n        if (!pick) { const safe = free.filter(([k, i]) => boxesOf(k, i).every(bi => sides(bi) < 2)); pick = (safe.length ? safe : free)[api.rand(0, (safe.length ? safe : free).length - 1)]; }",
    "let pick = diff === 0 && Math.random() < 0.5 ? null : free.find(([k, i]) => boxesOf(k, i).some(bi => sides(bi) === 3));\n        if (!pick) { if (diff === 0) pick = free[api.rand(0, free.length - 1)]; else { const safe = free.filter(([k, i]) => boxesOf(k, i).every(bi => sides(bi) < 2)); if (safe.length) pick = safe[api.rand(0, safe.length - 1)]; else if (diff === 2) { const cost = ([k, i]) => { const arr = k === 'h' ? hl : vl; arr[i] = 2; let got = 0; boxesOf(k, i).forEach(bi => { if (sides(bi) === 3) got++; }); arr[i] = 0; return got; }; pick = free.slice().sort((a2, b2) => cost(a2) - cost(b2))[0]; } else pick = free[api.rand(0, free.length - 1)]; } }")
rep("      start();\n    }\n  });\n\n  /* ---------- Морской бой ---------- */","      api.difficulty('dots', d => { diff = d; start(); });\n    }\n  });\n\n  /* ---------- Морской бой ---------- */")
# battleship
rep("let my, ai, myShots, aiShots, over, cells, aiCells, st = stats(api, 'battleship'), aiQueue = [], hdr;","let my, ai, myShots, aiShots, over, cells, aiCells, st = stats(api, 'battleship'), aiQueue = [], hdr, diff = 1;")
rep("if (over) return; let i; if (aiQueue.length) i = aiQueue.shift(); else { do { i = api.rand(0, 99); } while (aiShots[i]); }",
    "if (over) return; let i; if (aiQueue.length && diff > 0) i = aiQueue.shift(); else { const cand = [...Array(100).keys()].filter(k => !aiShots[k] && (diff < 2 || (Math.floor(k / N) + k % N) % 2 === 0)); const pool = cand.length ? cand : [...Array(100).keys()].filter(k => !aiShots[k]); i = pool[api.rand(0, pool.length - 1)]; }")
rep("if (my[i]) { const r = Math.floor(i / N), c = i % N; [[r - 1, c], [r + 1, c], [r, c - 1], [r, c + 1]].forEach(([rr, cc]) => { if (rr >= 0 && cc >= 0 && rr < N && cc < N && !aiShots[rr * N + cc]) aiQueue.push(rr * N + cc); }); api.sound('bad'); }",
    "if (my[i]) { const r = Math.floor(i / N), c = i % N; let nb = [[r - 1, c], [r + 1, c], [r, c - 1], [r, c + 1]]; if (diff === 2) { const hitN = [[r - 1, c], [r + 1, c]].some(([rr, cc]) => rr >= 0 && rr < N && aiShots[rr * N + cc] && my[rr * N + cc]); const hitW = [[r, c - 1], [r, c + 1]].some(([rr, cc]) => cc >= 0 && cc < N && aiShots[rr * N + cc] && my[rr * N + cc]); if (hitN) nb = [[r - 1, c], [r + 1, c]]; else if (hitW) nb = [[r, c - 1], [r, c + 1]]; } nb.forEach(([rr, cc]) => { if (rr >= 0 && cc >= 0 && rr < N && cc < N && !aiShots[rr * N + cc]) aiQueue.unshift(rr * N + cc); }); api.sound('bad'); }")
rep("      start();\n    }\n  });\n\n  /* ---------- Шашки ---------- */","      api.difficulty('battleship', d => { diff = d; start(); });\n    }\n  });\n\n  /* ---------- Шашки ---------- */")
# checkers
rep("let b, sel = -1, cells, over, st = stats(api, 'checkers'), mustFrom = -1;","let b, sel = -1, cells, over, st = stats(api, 'checkers'), mustFrom = -1, diff = 1;")
rep("while (true) { const lm = legal(b, 2, from); if (!lm.length) break; let best = lm[0], bv = -Infinity; for (const m of lm) { const g = b.slice(); apply(g, m); let v = (m.cap >= 0 ? 10 : 0) + Math.random() * 2 + (Math.floor(m.to / 8) === 7 ? 5 : 0); const reply = legal(g, 1, -1).filter(x => x.cap >= 0); v -= reply.length * 6; if (v > bv) { bv = v; best = m; } } apply(b, best);",
    "const evalG = g => g.reduce((s, v) => s + (v ? (v % 10 === 2 ? 1 : -1) * (king(v) ? 3 : 1) : 0), 0); const search = (g, pl, depth) => { const lm = legal(g, pl, -1); if (!depth || !lm.length) return evalG(g) + (lm.length ? 0 : (pl === 2 ? -50 : 50)); let best = pl === 2 ? -Infinity : Infinity; for (const m of lm) { const g2 = g.slice(); apply(g2, m); const v = search(g2, 3 - pl, depth - 1); best = pl === 2 ? Math.max(best, v) : Math.min(best, v); } return best; };\n        while (true) { const lm = legal(b, 2, from); if (!lm.length) break; let best = lm[0], bv = -Infinity; for (const m of lm) { const g = b.slice(); apply(g, m); let v; if (diff === 0) v = Math.random() * 10 + (m.cap >= 0 ? 3 : 0); else if (diff === 1) { v = (m.cap >= 0 ? 10 : 0) + Math.random() * 2 + (Math.floor(m.to / 8) === 7 ? 5 : 0); const reply = legal(g, 1, -1).filter(x => x.cap >= 0); v -= reply.length * 6; } else v = search(g, 1, 3) + Math.random() * 0.1; if (v > bv) { bv = v; best = m; } } apply(b, best);")
rep("      start();\n    }\n  });\n\n  /* ---------- Блэкджек (21) ---------- */","      api.difficulty('checkers', d => { diff = d; start(); });\n    }\n  });\n\n  /* ---------- Блэкджек (21) ---------- */")
# rps
rep("const { h } = api; const OPT = ['✊', '✌️', '✋']; let me, pc, hist = [], last = '', st = stats(api, 'rps');","const { h } = api; const OPT = ['✊', '✌️', '✋']; let me, pc, hist = [], last = '', st = stats(api, 'rps'), diff = 1;")
rep("let ai; if (hist.length >= 3 && Math.random() < 0.6) { const c = [0, 0, 0]; hist.slice(-6).forEach(x => c[x]++); const likely = c.indexOf(Math.max(...c)); ai = (likely + 2) % 3; } else ai = api.rand(0, 2);",
    "let ai; if (diff === 0) { ai = Math.random() < 0.5 ? (i + 1) % 3 : api.rand(0, 2); } else if (hist.length >= (diff === 2 ? 2 : 3) && Math.random() < (diff === 2 ? 0.9 : 0.6)) { const c = [0, 0, 0]; hist.slice(-6).forEach(x => c[x]++); if (diff === 2) c[hist[hist.length - 1]] += 1.5; const likely = c.indexOf(Math.max(...c)); ai = (likely + 2) % 3; } else ai = api.rand(0, 2);")
rep("      start();\n    }\n  });\n\n  /* ---------- Ним ---------- */","      api.difficulty('rps', d => { diff = d; start(); });\n    }\n  });\n\n  /* ---------- Ним ---------- */")
# nim
rep("const { h } = api; let n, st = stats(api, 'nim'), over;","const { h } = api; let n, st = stats(api, 'nim'), over, diff = 1;")
rep("setTimeout(() => { let t = (n - 1) % 4; if (t === 0) t = api.rand(1, Math.min(3, n));","setTimeout(() => { let t = (n - 1) % 4; if (t === 0 || diff === 0 || (diff === 1 && Math.random() < 0.35)) t = api.rand(1, Math.min(3, n));")
rep("      start();\n    }\n  });\n})();","      api.difficulty('nim', d => { diff = d; start(); });\n    }\n  });\n})();")
open(p,'w',encoding='utf-8').write(s); print('board ok')
